// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropertyInventorySystem.Data;

#nullable disable

namespace PropertyInventorySystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240621081824_DbInitialCreate")]
    partial class DbInitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PropertyInventorySystem.Models.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1f55e64-d1a1-4fe7-80b2-bac0c18a109a"),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PhoneNumber = "123456789"
                        },
                        new
                        {
                            Id = new Guid("033367b4-2a20-4c05-bec1-daf35cbadd88"),
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PhoneNumber = "987654321"
                        });
                });

            modelBuilder.Entity("PropertyInventorySystem.Models.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfRegistration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9ead71af-ee38-415c-a160-6f27bf7cfe38"),
                            Address = "123 Main St",
                            DateOfRegistration = new DateTime(2024, 6, 21, 10, 18, 23, 725, DateTimeKind.Local).AddTicks(6937),
                            Name = "Maisonette",
                            Price = 130000m
                        },
                        new
                        {
                            Id = new Guid("ad46dc38-d03b-455d-b91f-5e494d3c03ee"),
                            Address = "456 Elm St",
                            DateOfRegistration = new DateTime(2024, 6, 21, 10, 18, 23, 725, DateTimeKind.Local).AddTicks(6998),
                            Name = "Penthouse",
                            Price = 430000m
                        });
                });

            modelBuilder.Entity("PropertyInventorySystem.Models.SoldProperty", b =>
                {
                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AcquisitionPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateOfRegistration")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTill")
                        .HasColumnType("datetime2");

                    b.HasKey("PropertyId", "ContactId");

                    b.HasIndex("ContactId");

                    b.ToTable("SoldProperties");

                    b.HasData(
                        new
                        {
                            PropertyId = new Guid("9ead71af-ee38-415c-a160-6f27bf7cfe38"),
                            ContactId = new Guid("a1f55e64-d1a1-4fe7-80b2-bac0c18a109a"),
                            AcquisitionPrice = 120000m,
                            DateOfRegistration = new DateTime(2024, 5, 22, 10, 18, 23, 725, DateTimeKind.Local).AddTicks(7033)
                        },
                        new
                        {
                            PropertyId = new Guid("ad46dc38-d03b-455d-b91f-5e494d3c03ee"),
                            ContactId = new Guid("033367b4-2a20-4c05-bec1-daf35cbadd88"),
                            AcquisitionPrice = 420000m,
                            DateOfRegistration = new DateTime(2024, 6, 6, 10, 18, 23, 725, DateTimeKind.Local).AddTicks(7039)
                        });
                });

            modelBuilder.Entity("PropertyInventorySystem.Models.SoldProperty", b =>
                {
                    b.HasOne("PropertyInventorySystem.Models.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyInventorySystem.Models.Property", "Property")
                        .WithMany("SoldProperties")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropertyInventorySystem.Models.Property", b =>
                {
                    b.Navigation("SoldProperties");
                });
#pragma warning restore 612, 618
        }
    }
}
